apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tense-woodpecker-java-springboot 
  janus-idp.io/tekton: tense-woodpecker-java-springboot
  backstage.io/kubernetes-id: tense-woodpecker-java-springboot
  backstage.io/kubernetes-namespace: rhtap-integ 
  app.kubernetes.io/part-of: tense-woodpecker-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  